### ISSUE TITLE
Excpetions when trying to use quartznet10x5 and quartznet15x5

### ISSUE THREAD

**Issue by farisalasmary** [ivankunyankin/quartznet-asr#4]
Dear @ivankunyankin ,
I've run the code on quartznet5x5 and it worked! when I switched to use quartznet10x5 or quartznet15x5, I got the following exception:

```
Traceback (most recent call last):                                                                                                           
  File "train.py", line 392, in <module>                                                                                                     
    trainer.train()                                                                                                                          
  File "train.py", line 113, in train                                                                                                        
    self.train_step(epoch)                                                                                                                   
  File "train.py", line 163, in train_step                                                                                                   
    output = self.model(specs)                                                                                                               
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl                                         
    return forward_call(*input, **kwargs)                                                                                                    
  File "/workspace/quartznet-asr/models.py", line 42, in forward                                                                             
    x = block(x)                                                                                                                             
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl                                         
    return forward_call(*input, **kwargs)                                                                                                    
  File "/workspace/quartznet-asr/models.py", line 77, in forward                                                                             
    y = self.res(x)                                                                                                                          
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl                                         
    return forward_call(*input, **kwargs)                                                                                                    
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward                                          
    input = module(input)                                                                                                                    
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 301, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 297, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [512, 256, 1], expected input[64, 512, 101] to have 256 channels, but got 512 channels instead
```

Any idea?

**Comment by ivankunyankin** [comment]
@farisalasmary Hi! I'm truly sorry for the late response. I created another [branch](https://github.com/ivankunyankin/quartznet-asr/tree/issue-4-fix) with the fix of the problem. Could you verify that it works for you now?

**Comment by farisalasmary** [comment]
Hi @ivankunyankin,
Thank you for your reply!! I've tried it and it worked!!
Thank you again for your time
